# Generated by Django 4.1.5 on 2023-02-04 15:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemstore',
            name='time_update',
            field=models.DateTimeField(auto_now_add=True, verbose_name=datetime.datetime(2023, 2, 4, 15, 24, 26, 236931, tzinfo=datetime.timezone.utc)),
        ),
    ]
